databases:
  - name: database
    databaseName: ml_inference_db
    user: ml_user
    plan: free

services:
  - type: web
    name: ml-api
    env: docker
    dockerfilePath: ./docker/Dockerfile.api
    healthCheckPath: /health
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: database
          property: connectionString
      - key: MODEL_PATH
        value: models/trained_model.joblib
      - key: API_TITLE
        value: Real-Time ML Inference API
      - key: API_VERSION
        value: 1.0.0
      - key: LOG_LEVEL
        value: INFO
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 10000